# File: penguins_ai/config/optimal_settings.py
# Generated by system benchmark

SYSTEM_OPTIMAL_CONFIG = {
    # CPU Settings
    'xgboost_threads': 20,
    'cpu_parallel_jobs': 20,  # Leave some for system
    
    # Memory Settings  
    'max_memory_gb': 47,  # Use 75% of RAM
    'batch_size': 2048,
    
    # Model Complexity (based on your powerful system)
    'xgboost_config': {
        'n_estimators': 1000,  # More trees
        'max_depth': 12,       # Deeper trees
        'learning_rate': 0.01,
        'n_jobs': 20
    },
    
    # GPU Settings
    'use_gpu': True,
    'gpu_memory_fraction': 0.8,  # Use 80% of GPU memory
    
    # Data Processing
    'chunk_size': 100000,  # Process large chunks
    'enable_parallel_processing': True
}
